import Foundation

struct TranscriptionLanguage: Identifiable, Hashable {
    let name: String
    let code: String
    var id: String { code }
    
    static let all: [TranscriptionLanguage] = [
        TranscriptionLanguage(name: "Auto", code: "auto"),
        TranscriptionLanguage(name: "Afrikaans", code: "af"),
        TranscriptionLanguage(name: "Amharic", code: "am"),
        TranscriptionLanguage(name: "Arabic", code: "ar"),
        TranscriptionLanguage(name: "Armenian", code: "hy"),
        TranscriptionLanguage(name: "Assamese", code: "as"),
        TranscriptionLanguage(name: "Azerbaijani", code: "az"),
        TranscriptionLanguage(name: "Bashkir", code: "ba"),
        TranscriptionLanguage(name: "Belarusian", code: "be"),
        TranscriptionLanguage(name: "Bengali", code: "bn"),
        TranscriptionLanguage(name: "Bosnian", code: "bs"),
        TranscriptionLanguage(name: "Breton", code: "br"),
        TranscriptionLanguage(name: "Bulgarian", code: "bg"),
        TranscriptionLanguage(name: "Burmese", code: "my"),
        TranscriptionLanguage(name: "Catalan", code: "ca"),
        TranscriptionLanguage(name: "Chinese", code: "zh"),
        TranscriptionLanguage(name: "Croatian", code: "hr"),
        TranscriptionLanguage(name: "Czech", code: "cs"),
        TranscriptionLanguage(name: "Danish", code: "da"),
        TranscriptionLanguage(name: "Dutch", code: "nl"),
        TranscriptionLanguage(name: "English", code: "en"),
        TranscriptionLanguage(name: "Estonian", code: "et"),
        TranscriptionLanguage(name: "Faroese", code: "fo"),
        TranscriptionLanguage(name: "Finnish", code: "fi"),
        TranscriptionLanguage(name: "French", code: "fr"),
        TranscriptionLanguage(name: "Galician", code: "gl"),
        TranscriptionLanguage(name: "Georgian", code: "ka"),
        TranscriptionLanguage(name: "German", code: "de"),
        TranscriptionLanguage(name: "Greek", code: "el"),
        TranscriptionLanguage(name: "Gujarati", code: "gu"),
        TranscriptionLanguage(name: "Haitian Creole", code: "ht"),
        TranscriptionLanguage(name: "Hausa", code: "ha"),
        TranscriptionLanguage(name: "Hawaiian", code: "haw"),
        TranscriptionLanguage(name: "Hebrew", code: "he"),
        TranscriptionLanguage(name: "Hindi", code: "hi"),
        TranscriptionLanguage(name: "Hungarian", code: "hu"),
        TranscriptionLanguage(name: "Icelandic", code: "is"),
        TranscriptionLanguage(name: "Indonesian", code: "id"),
        TranscriptionLanguage(name: "Italian", code: "it"),
        TranscriptionLanguage(name: "Japanese", code: "ja"),
        TranscriptionLanguage(name: "Javanese", code: "jw"),
        TranscriptionLanguage(name: "Kannada", code: "kn"),
        TranscriptionLanguage(name: "Kazakh", code: "kk"),
        TranscriptionLanguage(name: "Khmer", code: "km"),
        TranscriptionLanguage(name: "Korean", code: "ko"),
        TranscriptionLanguage(name: "Lao", code: "lo"),
        TranscriptionLanguage(name: "Latin", code: "la"),
        TranscriptionLanguage(name: "Latvian", code: "lv"),
        TranscriptionLanguage(name: "Lingala", code: "ln"),
        TranscriptionLanguage(name: "Lithuanian", code: "lt"),
        TranscriptionLanguage(name: "Luxembourgish", code: "lb"),
        TranscriptionLanguage(name: "Macedonian", code: "mk"),
        TranscriptionLanguage(name: "Malagasy", code: "mg"),
        TranscriptionLanguage(name: "Malay", code: "ms"),
        TranscriptionLanguage(name: "Malayalam", code: "ml"),
        TranscriptionLanguage(name: "Maltese", code: "mt"),
        TranscriptionLanguage(name: "Maori", code: "mi"),
        TranscriptionLanguage(name: "Marathi", code: "mr"),
        TranscriptionLanguage(name: "Mongolian", code: "mn"),
        TranscriptionLanguage(name: "Nepali", code: "ne"),
        TranscriptionLanguage(name: "Norwegian", code: "no"),
        TranscriptionLanguage(name: "Norwegian Nynorsk", code: "nn"),
        TranscriptionLanguage(name: "Occitan", code: "oc"),
        TranscriptionLanguage(name: "Pashto", code: "ps"),
        TranscriptionLanguage(name: "Persian", code: "fa"),
        TranscriptionLanguage(name: "Polish", code: "pl"),
        TranscriptionLanguage(name: "Portuguese", code: "pt"),
        TranscriptionLanguage(name: "Punjabi", code: "pa"),
        TranscriptionLanguage(name: "Romanian", code: "ro"),
        TranscriptionLanguage(name: "Russian", code: "ru"),
        TranscriptionLanguage(name: "Sanskrit", code: "sa"),
        TranscriptionLanguage(name: "Serbian", code: "sr"),
        TranscriptionLanguage(name: "Shona", code: "sn"),
        TranscriptionLanguage(name: "Sindhi", code: "sd"),
        TranscriptionLanguage(name: "Sinhala", code: "si"),
        TranscriptionLanguage(name: "Slovak", code: "sk"),
        TranscriptionLanguage(name: "Slovenian", code: "sl"),
        TranscriptionLanguage(name: "Somali", code: "so"),
        TranscriptionLanguage(name: "Spanish", code: "es"),
        TranscriptionLanguage(name: "Sundanese", code: "su"),
        TranscriptionLanguage(name: "Swahili", code: "sw"),
        TranscriptionLanguage(name: "Swedish", code: "sv"),
        TranscriptionLanguage(name: "Tagalog", code: "tl"),
        TranscriptionLanguage(name: "Tajik", code: "tg"),
        TranscriptionLanguage(name: "Tamil", code: "ta"),
        TranscriptionLanguage(name: "Tatar", code: "tt"),
        TranscriptionLanguage(name: "Telugu", code: "te"),
        TranscriptionLanguage(name: "Thai", code: "th"),
        TranscriptionLanguage(name: "Tibetan", code: "bo"),
        TranscriptionLanguage(name: "Turkish", code: "tr"),
        TranscriptionLanguage(name: "Turkmen", code: "tk"),
        TranscriptionLanguage(name: "Ukrainian", code: "uk"),
        TranscriptionLanguage(name: "Urdu", code: "ur"),
        TranscriptionLanguage(name: "Uzbek", code: "uz"),
        TranscriptionLanguage(name: "Vietnamese", code: "vi"),
        TranscriptionLanguage(name: "Welsh", code: "cy"),
        TranscriptionLanguage(name: "Yiddish", code: "yi"),
        TranscriptionLanguage(name: "Yoruba", code: "yo"),
        TranscriptionLanguage(name: "Zulu", code: "zu")
    ]
}
