import Foundation

struct TranscriptionLanguage: Identifiable, Hashable {
    let name: String
    let code: String
    var id: String { code }
    
    static let all: [TranscriptionLanguage] = [
        TranscriptionLanguage(name: "Auto", code: "auto"),
        TranscriptionLanguage(name: "Afrikaans", code: "AF"),
        TranscriptionLanguage(name: "Albanian", code: "SQ"),
        TranscriptionLanguage(name: "Amharic", code: "AM"),
        TranscriptionLanguage(name: "Arabic", code: "AR"),
        TranscriptionLanguage(name: "Armenian", code: "HY"),
        TranscriptionLanguage(name: "Assamese", code: "AS"),
        TranscriptionLanguage(name: "Azerbaijani", code: "AZ"),
        TranscriptionLanguage(name: "Basque", code: "EU"),
        TranscriptionLanguage(name: "Bashkir", code: "BA"),
        TranscriptionLanguage(name: "Belarusian", code: "BE"),
        TranscriptionLanguage(name: "Bengali", code: "BN"),
        TranscriptionLanguage(name: "Bosnian", code: "BS"),
        TranscriptionLanguage(name: "Breton", code: "BR"),
        TranscriptionLanguage(name: "Bulgarian", code: "BG"),
        TranscriptionLanguage(name: "Burmese", code: "MY"),
        TranscriptionLanguage(name: "Catalan", code: "CA"),
        TranscriptionLanguage(name: "Chinese (Simplified)", code: "zh"),
        TranscriptionLanguage(name: "Chinese (Traditional)", code: "zh-Hant"),
        TranscriptionLanguage(name: "Croatian", code: "HR"),
        TranscriptionLanguage(name: "Czech", code: "CS"),
        TranscriptionLanguage(name: "Danish", code: "DA"),
        TranscriptionLanguage(name: "Dutch", code: "NL"),
        TranscriptionLanguage(name: "English (US)", code: "en"),
        TranscriptionLanguage(name: "English (UK)", code: "en-gb"),
        TranscriptionLanguage(name: "Estonian", code: "ET"),
        TranscriptionLanguage(name: "Faroese", code: "FO"),
        TranscriptionLanguage(name: "Finnish", code: "FI"),
        TranscriptionLanguage(name: "French", code: "FR"),
        TranscriptionLanguage(name: "Galician", code: "GL"),
        TranscriptionLanguage(name: "Georgian", code: "KA"),
        TranscriptionLanguage(name: "German", code: "DE"),
        TranscriptionLanguage(name: "Greek", code: "EL"),
        TranscriptionLanguage(name: "Gujarati", code: "GU"),
        TranscriptionLanguage(name: "Haitian Creole", code: "HT"),
        TranscriptionLanguage(name: "Hausa", code: "HA"),
        TranscriptionLanguage(name: "Hawaiian", code: "HAW"),
        TranscriptionLanguage(name: "Hebrew", code: "HE"),
        TranscriptionLanguage(name: "Hindi", code: "HI"),
        TranscriptionLanguage(name: "Hungarian", code: "HU"),
        TranscriptionLanguage(name: "Icelandic", code: "IS"),
        TranscriptionLanguage(name: "Indonesian", code: "ID"),
        TranscriptionLanguage(name: "Irish", code: "GA"),
        TranscriptionLanguage(name: "Italian", code: "IT"),
        TranscriptionLanguage(name: "Japanese", code: "JA"),
        TranscriptionLanguage(name: "Javanese", code: "JW"),
        TranscriptionLanguage(name: "Kannada", code: "KN"),
        TranscriptionLanguage(name: "Kazakh", code: "KK"),
        TranscriptionLanguage(name: "Khmer", code: "KM"),
        TranscriptionLanguage(name: "Korean", code: "KO"),
        TranscriptionLanguage(name: "Lao", code: "LO"),
        TranscriptionLanguage(name: "Latin", code: "LA"),
        TranscriptionLanguage(name: "Latvian", code: "LV"),
        TranscriptionLanguage(name: "Lingala", code: "LN"),
        TranscriptionLanguage(name: "Lithuanian", code: "LT"),
        TranscriptionLanguage(name: "Luxembourgish", code: "LB"),
        TranscriptionLanguage(name: "Macedonian", code: "MK"),
        TranscriptionLanguage(name: "Malagasy", code: "MG"),
        TranscriptionLanguage(name: "Malay", code: "MS"),
        TranscriptionLanguage(name: "Malayalam", code: "ML"),
        TranscriptionLanguage(name: "Maltese", code: "MT"),
        TranscriptionLanguage(name: "Maori", code: "MI"),
        TranscriptionLanguage(name: "Marathi", code: "MR"),
        TranscriptionLanguage(name: "Mongolian", code: "MN"),
        TranscriptionLanguage(name: "Nepali", code: "NE"),
        TranscriptionLanguage(name: "Norwegian (Bokmål)", code: "NB"),
        TranscriptionLanguage(name: "Norwegian Nynorsk", code: "NN"),
        TranscriptionLanguage(name: "Occitan", code: "OC"),
        TranscriptionLanguage(name: "Pashto", code: "PS"),
        TranscriptionLanguage(name: "Persian", code: "FA"),
        TranscriptionLanguage(name: "Polish", code: "PL"),
        TranscriptionLanguage(name: "Portuguese (BR)", code: "pt"),
        TranscriptionLanguage(name: "Portuguese (PT)", code: "pt"),
        TranscriptionLanguage(name: "Punjabi", code: "PA"),
        TranscriptionLanguage(name: "Romanian", code: "RO"),
        TranscriptionLanguage(name: "Russian", code: "RU"),
        TranscriptionLanguage(name: "Sanskrit", code: "SA"),
        TranscriptionLanguage(name: "Serbian", code: "SR"),
        TranscriptionLanguage(name: "Shona", code: "SN"),
        TranscriptionLanguage(name: "Sindhi", code: "SD"),
        TranscriptionLanguage(name: "Sinhala", code: "SI"),
        TranscriptionLanguage(name: "Slovak", code: "SK"),
        TranscriptionLanguage(name: "Slovenian", code: "SL"),
        TranscriptionLanguage(name: "Somali", code: "SO"),
        TranscriptionLanguage(name: "Spanish", code: "ES"),
        TranscriptionLanguage(name: "Sundanese", code: "SU"),
        TranscriptionLanguage(name: "Swahili", code: "SW"),
        TranscriptionLanguage(name: "Swedish", code: "SV"),
        TranscriptionLanguage(name: "Tagalog", code: "TL"),
        TranscriptionLanguage(name: "Tajik", code: "TG"),
        TranscriptionLanguage(name: "Tamil", code: "TA"),
        TranscriptionLanguage(name: "Tatar", code: "TT"),
        TranscriptionLanguage(name: "Telugu", code: "TE"),
        TranscriptionLanguage(name: "Thai", code: "TH"),
        TranscriptionLanguage(name: "Tibetan", code: "BO"),
        TranscriptionLanguage(name: "Turkish", code: "TR"),
        TranscriptionLanguage(name: "Turkmen", code: "TK"),
        TranscriptionLanguage(name: "Ukrainian", code: "UK"),
        TranscriptionLanguage(name: "Urdu", code: "UR"),
        TranscriptionLanguage(name: "Uzbek", code: "UZ"),
        TranscriptionLanguage(name: "Vietnamese", code: "VI"),
        TranscriptionLanguage(name: "Welsh", code: "CY"),
        TranscriptionLanguage(name: "Yiddish", code: "YI"),
        TranscriptionLanguage(name: "Yoruba", code: "YO"),
        TranscriptionLanguage(name: "Zulu", code: "ZU")
    ]
}
